### ISSUE TITLE
Please sir, can I have some docs?

### ISSUE THREAD

**Issue by phillcoppock** [cloudpups/github-teams-user-sync#16]
What would I need to change/update to leverage this in a new GHEC Enterprise against a new LDAP environment?

---

- [x] Development requirements
- [x] Running app locally
- [ ] ~Debugging tips and tricks~
- [x] Running app in production (this should cover the question above)

**Comment by JoshuaTheMiller** [comment]
Icons for docs? 🤔

![GttSB_Icon](https://github.com/cloudpups/github-teams-user-sync/assets/4266541/e4b9bf9b-c4e8-4824-a60c-d7e28034ebc1)
![GttSB_Icon_Small](https://github.com/cloudpups/github-teams-user-sync/assets/4266541/e2e6fc5a-51b8-4b20-9ca6-d94e28baca41)
