### ISSUE TITLE
Feature Suggestion: Org Owners

### ISSUE THREAD

**Issue by amyschoen** [cloudpups/github-teams-user-sync#30]
It would be great to have the functionality to denote a group of people as the org owners.  It would save a lot of manual effort as we add additional org owners to our larger orgs.

For this to work properly, we wouldn't want to remove org owner rights if they fall out of the existing group.  That would put us at risk of having an unmanageable org if we have a sync failure.  I would prefer removing org owners manually when needed.

**Comment by JoshuaTheMiller** [comment]
An excellent idea!

I enjoy the idea of starting such a feature off as a "will add Owners only" and leaving the more destructive/disruptive actions for manual intervention.

Rectifying owners with the "owners group" can be a separate feature 😀
